### ISSUE TITLE
编辑源码保存后，报错

### ISSUE THREAD

**Issue by SteveCGC** [KNXCloud/lowcode-engine-vue#10]
![image](https://user-images.githubusercontent.com/16144832/176404304-d67925f6-9abc-42ac-9f80-a099e969b780.png)
1. 新增了一个 count变量，点击按钮后，count+1
2. 拖入一个文本组件，文本内容绑定this.state.count，控制台直接报错，文本组件也不显示了

需要适配代码编辑器吗？

**Comment by SteveCGC** [comment]
貌似所有的变量绑定功能都无法使用

**Comment by keuby** [comment]
内容绑定值，`this.state.count` -> `this.count`

**Comment by SteveCGC** [comment]
确实可以，但是变量绑定弹框中，可选的变量都带着this.state，是不是要修改VariableSetter

**Comment by keuby** [comment]
可以对 VariableSetter 做一定适配，以获得更好的交互体验，demo 中`ExpressionSetter` 就做了适配
