### ISSUE TITLE
画布国际化有点问题

### ISSUE THREAD

**Issue by JimFirst** [KNXCloud/lowcode-engine-vue#23]
element-plus locale应该是一个对象
![image](https://user-images.githubusercontent.com/19401131/177953280-b7b81eff-0ffe-40ff-9ad7-63fbc53f86bd.png)，
demo项目的国际化也有问题，vue-renderer组件的props.locale默认为undefined，会覆盖demo configProvide传过去的locale
![image](https://user-images.githubusercontent.com/19401131/177953568-f3cf5c44-017a-493d-8bb7-1dfad7417b0b.png)
![image](https://user-images.githubusercontent.com/19401131/177953676-66aa91a4-c500-4559-b900-0fb1320a850e.png)

**Comment by keuby** [comment]
添加 inheritAttrs 属性即可，demo 已更新

![image](https://user-images.githubusercontent.com/32365592/178523293-d7e5d9be-2cfe-4d27-9c22-afb49ff48157.png)
