### ISSUE TITLE
支持Template、Block、Component结构

### ISSUE THREAD

**Issue by zboMa** [KNXCloud/lowcode-engine-vue#34]
# 说明
目前vue-renderer中只实现了Page结构的物料规范，其他类型的物料未实现，请求实现。

# 协议地址
https://lowcode-engine.cn/lowcode
# 相关说明位置
## 低代码引擎搭建协议规范
+ 1.6.1 物料系统名词
+ 2.3 组件树描述 关于容器结构的描述
+ 2.3.3 容器结构描述
+ 2.3.5.1 容器API
+ 3 应用描述

## 低代码引擎物料协议规范
+ 1.6 名词术语
+ 3 物料规范-区块规范
+ 4 物料规范-模板规范

**Comment by keuby** [comment]
v1.6.0-beta.3
