### ISSUE TITLE
vue 代码编辑器有适配计划吗

### ISSUE THREAD

**Issue by SteveCGC** [KNXCloud/lowcode-engine-vue#4]
vue 代码编辑器有适配计划吗

**Comment by keuby** [comment]
有的，后面会适配 vue 的编辑器以及出码，具体时间点暂时无法给出，欢迎共创。

**Comment by SteveCGC** [comment]
里面的出码和编辑器都得用React去写吧，无法直接用vue啊

**Comment by keuby** [comment]
插件用 react 写，只是适配 vue 的功能

**Comment by SteveCGC** [comment]
方便建个讨论群吗？一块交流下

**Comment by keuby** [comment]
> 方便建个讨论群吗？一块交流下

微信搜索: cjf395782896，加好友&备注：低代码引擎，申请入群
