### ISSUE TITLE
如果在运行过程调用material.setAssets 更改 assets，会导致组件找不到

### ISSUE THREAD

**Issue by winixt** [KNXCloud/lowcode-engine-vue#48]
lowcode 有没暴露方法给 host 让我们监听到 assets 变更的时候，重新build一下？
![image](https://user-images.githubusercontent.com/20717402/224485803-23b150d6-db98-4273-9113-12d6d8d78235.png)

**Comment by winixt** [comment]
debug 跟了一下，host.designer.componentsMap 压根没更新～

**Comment by winixt** [comment]
排查到问题了，需要给 simulator 加个 load 方法给 lowcode host 的 setupComponents 调用
![image](https://user-images.githubusercontent.com/20717402/224527491-e3b2370d-c657-450b-87d2-76c96bbd3ef4.png)

![image](https://user-images.githubusercontent.com/20717402/224527515-b2c09fa1-1d87-43f3-827c-808bafd8a4fc.png)

@keuby 帮忙看下，处理好了麻烦帮忙搞个版本，我这边急用

**Comment by keuby** [comment]
试一下 1.6.0-beta.2 版本
