### ISSUE TITLE
element-plus物料接入问题

### ISSUE THREAD

**Issue by JimFirst** [KNXCloud/lowcode-engine-vue#6]
有fork过去，尝试了一下接入一下element-plus的物料，发现由于element-plus物料是用<script setup>的语法糖写的，接入会有问题，这边的lowcode-vue-simulator-renderer可能需要适配一下

**Comment by keuby** [comment]
好的，已经发现问题了，正在修复中

**Comment by keuby** [comment]
release v1.1.1

**Comment by JimFirst** [comment]
> release v1.1.1

效率真高，下午试试

**Comment by JimFirst** [comment]
兄弟，你这修复的有点草率，老的都不能用了。导致bug的原因是 
1. render函数抛出来的实例对象是一个 vnode，naive-ui是这种写法；
2. element-plus抛出来的是由[defineExpose](https://v3.cn.vuejs.org/api/sfc-script-setup.html#defineprops-%E5%92%8C-defineemits)抛出来的属性对象，两者的对象结构不一样。

**Comment by keuby** [comment]
> 兄弟，你这修复的有点草率，老的都不能用了。导致bug的原因是
> 
> 1. render函数抛出来的实例对象是一个 vnode，naive-ui是这种写法；
> 2. element-plus抛出来的是由[defineExpose](https://v3.cn.vuejs.org/api/sfc-script-setup.html#defineprops-%E5%92%8C-defineemits)抛出来的属性对象，两者的对象结构不一样。

这个是 vue 的 expose 机制导致的，目前正在查找解决办法
