### ISSUE TITLE
vue插槽渲染组件中使用this获取插槽传过来的值不生效

### ISSUE THREAD

**Issue by daly-web** [KNXCloud/lowcode-engine-vue#62]
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/20960944/829dbcda-7c7a-4cb6-85f4-1c515dd6f9de)
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/20960944/f88caf71-8742-4116-a260-3b12fe880667)
我使用的是antd-vue组件库生成的物料，在设置table的expandedRowRender属性时，使用slot,拖进去一个成功提示的组件，然后自定义成功提示组件的描述性息和警告提示内容变量，使用的是slot传值过来的record和index属性，通过this.record和this.index获取，但是不生效

**Comment by keuby** [comment]
vue3 会将插槽编译成一个函数，这边的插槽参数是函数的参数名称，数组的列表是参数列表。Slot 传入的 `record`, `index` 等属性应该都是第一个参数的属性，可以考虑这样设置

```js
{
  componentName: 'SlotSetter',
  initialValue: {
    params: ['data']
  }
}
```

```js
this.data.record;
this.data.index;
```

**Comment by lyllovelemon** [comment]
> vue3 会将插槽编译成一个函数，这边的插槽参数是函数的参数名称，数组的列表是参数列表。Slot 传入的 `record`, `index` 等属性应该都是第一个参数的属性，可以考虑这样设置
> 
> ```js
> {
>   componentName: 'SlotSetter',
>   initialValue: {
>     params: ['data']
>   }
> }
> ```
> 
> ```js
> this.data.record;
> this.data.index;
> ```

design模式（画布模式）正常展示（已解决）
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/31084471/aaaa8aa6-c351-4471-8533-9ebebf0677e9)

live模式（预览模式）报错
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/31084471/72933e4b-8137-4232-96ce-c2ac0b5d61db)
