### ISSUE TITLE
自定义物料无法拖拽到页面，报错

### ISSUE THREAD

**Issue by lyllovelemon** [KNXCloud/lowcode-engine-vue#64]
复现步骤：
1. 运行demo项目
2. 拖入简单列表组件
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/31084471/891f5f61-4401-45f3-9340-7b82eaa36a7d)
3.控制台报错
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/31084471/77300edf-e759-43d8-95e9-248136b07690)

版本信息
@knxcloud/lowcode-plugin-vue-code-editor：v 0.0.1-beta.6,
@knxcloud/lowcode-utils  v1.6.0-beta.5,
@knxcloud/lowcode-vue-renderer: v1.6.0-beta.7,
@knxcloud/lowcode-vue-simulator-renderer: v1.6.0-beta.7,
AliLowCodeEngine:v1.1.7-beta ,
 AliLowCodeExt:v1.0.6-beta.27

**Comment by lyllovelemon** [comment]
AList的meta定义：
https://github.com/lyllovelemon/lowcode-material-ant-vue/blob/main/src/lowcode/list/meta.ts

AListItem的meta定义:
https://github.com/lyllovelemon/lowcode-material-ant-vue/blob/main/src/lowcode/list-item/meta.ts

AListItemMeta的meta定义:
https://github.com/lyllovelemon/lowcode-material-ant-vue/blob/main/src/lowcode/list-item-meta/meta.ts

项目快速复现路径：
1. git clone https://github.com/lyllovelemon/lowcode-vue-demo
2. pnpm install
3. pnpm start
4. 打开控制台
5. 拖入简单列表组件

**Comment by keuby** [comment]
自定义组件是函数式组件吗？

**Comment by lyllovelemon** [comment]
> 自定义组件是函数式组件吗？

ant-design-vue的lowcode描述

**Comment by keuby** [comment]
fixed in v1.6.0-beta.9

**Comment by lyllovelemon** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
