### ISSUE TITLE
Design模式下，插槽内容，你使用了<div class="lc-container">包裹了插槽内容，这样在编辑时，插槽内容应该行内展示的，却变成块级换行了

### ISSUE THREAD

**Issue by daly-web** [KNXCloud/lowcode-engine-vue#66]
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/20960944/10a5cc0a-d4ec-4a9f-bda3-5fdd2c57f2b4)
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/20960944/d1ee6fca-8e35-4db6-aea0-bd6f51629720)

**Comment by daly-web** [comment]
live模式下没有使用<div class="lc- container">进行包裹

**Comment by iDayMonthYear** [comment]
我也遇到了，react 的没有这个问题。

**Comment by keuby** [comment]
fixed in v1.6.0-beta.9
