### ISSUE TITLE
JSSlot  传递变量 渲染在子组件上， 在编辑器是正常的， 但是预览后的 渲染器 不正常渲染内容

### ISSUE THREAD

**Issue by che-my** [KNXCloud/lowcode-engine-vue#69]
![250ce782e5dcbdc12c952186c91a758](https://github.com/KNXCloud/lowcode-engine-vue/assets/34227778/ee214de6-194a-4a1c-a79a-b496517a1422)
![c87340c061cc89a4f08400bed767362](https://github.com/KNXCloud/lowcode-engine-vue/assets/34227778/2ec26e8d-7845-410b-8fce-4003df733a75)

**Comment by che-my** [comment]
### 我查看了仓库源码 和线上版本1.6.0-beta.8源码,   线上版本1.6.0-beta.8不是最新打包的
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/34227778/a3ce4c7a-6028-4f32-84e0-434763a23548)

**Comment by keuby** [comment]
fixed in v1.6.0-beta.9
