### ISSUE TITLE
JSSlot 渲染 defineAsyncComponent 定义的组件时, 有警告信息, vue会报错 找不到 parentNode

### ISSUE THREAD

**Issue by che-my** [KNXCloud/lowcode-engine-vue#71]
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/34227778/19a4b39d-5ed8-4f5b-a475-1da26336e40a)

**Comment by keuby** [comment]
fixed in v1.6.0-beta.9

**Comment by PineSongCN** [comment]
> fixed in v1.6.0-beta.9

您好，请问 v1.6.0-beta.9 代码在哪里可以看？
