### ISSUE TITLE
生成的页面能否在单页面应用中直接使用

### ISSUE THREAD

**Issue by chengqy010612** [KNXCloud/lowcode-engine-vue#75]
我这边是想在已有的vue后台项目中使用，有的菜单是通过写代码生成的，有的是希望通过低代码编辑器生成，通过给菜单传入不同scheme生成对应的页面

**Comment by ZedCoding** [comment]
> 我这边是想在已有的vue后台项目中使用，有的菜单是通过写代码生成的，有的是希望通过低代码编辑器生成，通过给菜单传入不同scheme生成对应的页面

大佬你们这个需求有做出来吗？
