### ISSUE TITLE
请问ant-design-vue Table组件 bodyCell slot + if 的形式如何配置setter

### ISSUE THREAD

**Issue by PineSongCN** [KNXCloud/lowcode-engine-vue#76]
![image](https://github.com/KNXCloud/lowcode-engine-vue/assets/39976617/5b4898f5-bb0d-4b55-be3a-85e425a09882)

**Comment by PineSongCN** [comment]
?

**Comment by keuby** [comment]
使用 slotSetter 就好，内部的v-if 逻辑可以在面板右侧使用 Advance 里面的 condition 进行配置

**Comment by keuby** [comment]
如还有其他疑问，可以重新打开一个 issue，这个 issue 先关闭了
